apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  labels:
    app: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: taskflow/task-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: DB_HOST
              value: "host.minikube.internal"
            - name: DB_PORT
              value: "5433"
            - name: DB_NAME
              value: "taskflow"
            - name: DB_USER
              value: "taskflow"
            - name: DB_PASSWORD
              value: "taskflow"
            - name: REDIS_HOST
              value: "host.minikube.internal"
            - name: REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
