version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: taskflow-postgres
    environment:
      POSTGRES_DB:       taskflow
      POSTGRES_USER:     taskflow
      POSTGRES_PASSWORD: taskflow
    ports:
      - "5433:5432"   # host: use 5432 to avoid conflicts with the host
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskflow -d taskflow"]
      interval: 5s
      timeout:  5s
      retries: 5
    networks:
      - taskflow-network

  task-service:
    build:
      context: ../../task-service
      dockerfile: Dockerfile
    container_name: taskflow-task-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST:     postgres   # service name internal to the network
      DB_PORT:     5432       # container port
      DB_NAME:     taskflow
      DB_USER:     taskflow
      DB_PASSWORD: taskflow
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network

  user-service:
    build:
      context: ../../user-service
      dockerfile: Dockerfile
    container_name: taskflow-user-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST:     postgres
      DB_PORT:     5432
      DB_NAME:     taskflow_users
      DB_USER:     taskflow
      DB_PASSWORD: taskflow
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network

  api-gateway:
    build:
      context: ../../api-gateway
    container_name: taskflow-gateway
    environment:
      TASK_SERVICE_URL: http://task-service:8080
      USER_SERVICE_URL: http://user-service:8081
    ports:
      - "8090:8090"
    depends_on:
      - task-service
      - user-service
    networks:
      - taskflow-network

volumes:
  postgres-data:

networks:
  taskflow-network:
    driver: bridge
