spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL_MS:300000}

  application:
    name: task-service
  datasource:
    url:      jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:taskflow}
    username: ${DB_USER:taskflow}
    password: ${DB_PASSWORD:taskflow}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

services:
  user-service:
    url: {USER_SERVICE_URL:http://localhost:8081}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true