apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  TASK_SERVICE_URL: "http://task-service:8080"
  USER_SERVICE_URL: "http://user-service:8081"
