apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: taskflow/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: TASK_SERVICE_URL
              value: "http://task-service:8080"
            - name: USER_SERVICE_URL
              value: "http://user-service:8081"
